import sgMail from '@sendgrid/mail';

if (!process.env.SENDGRID_API_KEY) {
  console.warn("SENDGRID_API_KEY environment variable is not set");
} else {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);
}

export interface EmailOptions {
  to: string;
  subject: string;
  content: string;
  contentType?: 'html' | 'text';
}

export async function sendEmail(options: EmailOptions): Promise<void> {
  if (!process.env.SENDGRID_API_KEY) {
    throw new Error("SendGrid API key is not configured");
  }

  const { to, subject, content, contentType = 'html' } = options;
  
  const msg = {
    to,
    from: 'noreply@docmathai.app', // This should be a verified sender in SendGrid
    subject,
    ...(contentType === 'html' ? { html: content } : { text: content }),
  };

  try {
    await sgMail.send(msg);
    console.log(`Email sent successfully to ${to}`);
  } catch (error) {
    console.error('SendGrid error:', error);
    throw new Error('Failed to send email via SendGrid');
  }
}

export async function sendResponseEmail(content: string, userEmail?: string): Promise<void> {
  const email = userEmail || 'user@example.com'; // Default email for testing
  
  await sendEmail({
    to: email,
    subject: 'AI Response from DocMath AI',
    content: `
      <div style="font-family: Georgia, serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px;">
          AI Response - DocMath AI
        </h1>
        <div style="margin-top: 20px;">
          ${content}
        </div>
        <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;">
        <p style="color: #6b7280; font-size: 14px;">
          This response was generated by Living Book Creator. Mathematical notation is preserved in this email.
        </p>
      </div>
    `,
    contentType: 'html'
  });
}